
CREATE TABLE PUBLIC.SECU_USERS (
	USER_ID INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_2443178E_1799_416B_B907_280A6CD39E8D" NOT NULL AUTO_INCREMENT,
	PROF_ID INTEGER NOT NULL,
	USER_LOGIN VARCHAR(100) NOT NULL,
	USER_PASSWORD VARCHAR(50) NOT NULL,
	CONSTRAINT SECU_USERS_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_6 ON PUBLIC.SECU_USERS (USER_ID);
CREATE INDEX SECU_USERS_FK_INDEX_6 ON PUBLIC.SECU_USERS (PROF_ID);

ALTER TABLE PUBLIC.SECU_USERS ADD CONSTRAINT SECU_USERS_FK FOREIGN KEY (PROF_ID) REFERENCES PUBLIC.ORMA_PROFESSIONALS(PROF_ID) ON DELETE RESTRICT ON UPDATE RESTRICT;



CREATE TABLE PUBLIC.ORMA_PROFESSIONALS (
	PROF_ID INTEGER DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_36A78382_F55A_4F75_A2D5_DEEFCE3749FE" NOT NULL AUTO_INCREMENT,
	PROF_NAME VARCHAR(50) NOT NULL,
	PROF_SURNAME_1 VARCHAR(50),
	PROF_SURNAME_2 VARCHAR(50),
	PROF_ID_VALUE VARCHAR(100) NOT NULL,
	CONSTRAINT ORMA_PROFESSIONALS_PK PRIMARY KEY (PROF_ID)
);
CREATE UNIQUE INDEX ORMA_PROFESSIONALS_UN_INDEX_4 ON PUBLIC.ORMA_PROFESSIONALS (PROF_ID,PROF_ID_VALUE);
CREATE UNIQUE INDEX PRIMARY_KEY_4 ON PUBLIC.ORMA_PROFESSIONALS (PROF_ID);
